#!/usr/bin/env bash
# Displays DNS information for selected subdomains of a domain

display_record() {
    local fqdn="$1"
    local subdomain="$2"

    dig "$fqdn" | awk -v subdomain="$subdomain" '
        /ANSWER SECTION:/ {
            getline
            print "The subdomain " subdomain " is a " $4 " record and points to " $5
        }
    '
}

if [ -n "$2" ]; then
    display_record "$2.$1" "$2"
else
    for subdomain in www lb-01 web-01 web-02; do
        display_record "$subdomain.$1" "$subdomain"
    done
fi
