#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header X-Served-By

apt-get update
apt-get -y install nginx

sed -i '/X-Served-By/d' /etc/nginx/sites-enabled/default
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-enabled/default

service nginx restart
