#!/usr/bin/env bash
# Configures Nginx to send a custom served-by response header
apt-get update
apt-get -y install nginx
printf 'Holberton School\n' > /var/www/html/index.html
cat > /tmp/x_served_by <<'EOF'
    add_header X-Served-By $hostname;
EOF
sed -i '/server_name _;/r /tmp/x_served_by' /etc/nginx/sites-available/default
service nginx restart
