#!/usr/bin/env bash
# Configures Nginx to send a custom served-by response header
apt-get -y update
apt-get -y install nginx
printf 'Holberton School\n' > /var/www/html/index.html
sed -i "/server_name _;/a\
    add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
service nginx restart
