#!/usr/bin/env bash
# Installs and configures HAProxy on a load balancer
apt-get update
apt-get -y install haproxy
sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy
grep -q 'web-01' /etc/hosts || printf '3.84.150.52 web-01\n44.204.148.199 web-02\n' >> /etc/hosts
cat > /etc/haproxy/haproxy.cfg <<'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 web-01:80 check
    server web-02 web-02:80 check
EOF
service haproxy restart
