#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with 301
apt-get -y update
apt-get -y install nginx
printf 'Holberton School\n' > /var/www/html/index.html
cat <<'EOF' >/tmp/redirect_me_location
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
EOF
sed -i '/server_name _;/r /tmp/redirect_me_location' /etc/nginx/sites-available/default
service nginx restart
