#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with 301
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default
service nginx restart
