#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Write a clean Nginx config with redirect and custom 404
cat > /etc/nginx/sites-enabled/default << 'ENDCONFIG'
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;
	location = /404.html {
		root /var/www/html;
		internal;
	}
}
ENDCONFIG

service nginx restart
