#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add the redirect and error_page configurations to sites-available/default
# We use sed to insert them into the server block
sed -i '/server_name _;/a \	location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

service nginx restart
